### ISSUE TITLE
PyPESTO branch missing

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/mechanismEncoder#11]
This branch seems to be missing. Was this integrated into another branch? The build still fails using master.

https://github.com/meyer-lab/mechanismEncoder/blob/747558698b20255cf796ebd903d2cd086b19319d/requirements.txt#L17

**Comment by FFroehlich** [comment]
> This branch seems to be missing. Was this integrated into another branch? The build still fails using master.
> 
> https://github.com/meyer-lab/mechanismEncoder/blob/747558698b20255cf796ebd903d2cd086b19319d/requirements.txt#L17

Oh yes, that was finally merged. Not on master yet, but should work with `@develop`. Will fix shortly.
